name: Package Android SDK

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_BRANCH: 1.10.4

jobs:
  pkg-android-sdk:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Defold
        uses: actions/checkout@v4
        with:
          repository: defold/defold
          ref: ${{env.BUILD_BRANCH}}

      - name: Install Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: 3.13

      - name: Download Clang 16.0.0
        run: |
          mkdir -p local_sdks
          wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz" -O "./local_sdks/clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz"

      - name: Package SDK
        shell: bash
        run: ./scripts/package/package_android_sdk.sh

      - name: Package NDK
        shell: bash
        run: ./scripts/package/package_android_ndk.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: local_sdks
          path: local_sdks
          if-no-files-found: error
